### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by paulaberry** [FTD007/PInet#1]
after downloading and unzipping the files, and moving into the `PInet` directory, the command:

` $ python setup.py`

results in this output:

`usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]`
   `or: setup.py --help [cmd1 cmd2 ...]`
   `or: setup.py --help-commands`
   `or: setup.py cmd --help`

`error: no commands supplied`

**Comment by FTD007** [comment]
Could you try

python setup.py install

you might also need to specify the install directory in some cases.

From: Paula Berry ***@***.***>
Date: Monday, March 15, 2021 at 4:38 PM
To: FTD007/PInet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FTD007/PInet] setup.py error (#1)

after downloading and unzipping the files, and moving into the PInet directory, the command:

$ python setup.py

results in this output:

`usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help

error: no commands supplied`

**Comment by paulaberry** [comment]
Thank you, that appears to have worked! However, now when attempting to run the example with the command from the PInet directory:

`$ python utils/train_richdbd2_fixed6mmgk.py -dataset dbd`

I get this output:

`Traceback (most recent call last):`
  `File "utils/train_richdbd2_fixed6mmgk.py", line 10, in <module>`
    `from pointnet.dataset import ShapeNetDataset3aug`
`ModuleNotFoundError: No module named 'pointnet'`

**Comment by FTD007** [comment]
Ah sorry for this, I just fixed it. Could you pull again?

From: Paula Berry ***@***.***>
Date: Tuesday, March 16, 2021 at 12:32 PM
To: FTD007/PInet ***@***.***>
Cc: Bowen Dai ***@***.***>, Comment ***@***.***>
Subject: Re: [FTD007/PInet] setup.py error (#1)

Thank you, that appears to have worked! However, now when attempting to run the example with the command from the PInet directory:

$ python utils/train_richdbd2_fixed6mmgk.py -dataset dbd

I get this output:

Traceback (most recent call last):
File "utils/train_richdbd2_fixed6mmgk.py", line 10, in <module>
from pointnet.dataset import ShapeNetDataset3aug
ModuleNotFoundError: No module named 'pointnet'

**Comment by FTD007** [comment]
> Thank you, that appears to have worked! However, now when attempting to run the example with the command from the PInet directory:
> 
> `$ python utils/train_richdbd2_fixed6mmgk.py -dataset dbd`
> 
> I get this output:
> 
> `Traceback (most recent call last):`
> `File "utils/train_richdbd2_fixed6mmgk.py", line 10, in <module>`
> `from pointnet.dataset import ShapeNetDataset3aug`
> `ModuleNotFoundError: No module named 'pointnet'`

Hi paulaberry, I change the repo a little bit. It should works fine now

**Comment by paulaberry** [comment]
Hello - the updated version seems to install - I'm running into another issue with running the test training command, but as it doesn't appear to be a setup.py problem I will open another issue.
