### ISSUE TITLE
Dataloader Error

### ISSUE THREAD

**Issue by bbjy** [FTD007/PInet#7]
Thank you for your work! I have a problem when load the data with the 'dataloader_r' and 'dataloader_l'. Since the cloud points in receptor and ligand are different, there is an error when enumerate 'zip(dataloader_r, dataloader_l)' as following "RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 25819 and 14085 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:612".

Have you meet the same problem? Thank you.

https://github.com/FTD007/PInet/blob/a13978d2f80b4d3d869cbea8ed7ae635cb861be1/utils/train_richdbd2_fixed6mmgk.py#L179

**Comment by FTD007** [comment]
is your batch size 1?

**Comment by bbjy** [comment]
> is your batch size 1?

No. Since I ran the model as "python utils/train_richdbd2_fixed6mmgk.py -dataset [your dataset]" will occur " Segmentation Fault", I set the batch size as **4**, and ' data_augmentation=False,'. Then I occur the above error.

And I want to ask another problem, how to split a complex pdb file into the two 'ligand' and 'receptor' pdb files? As the instructions in README.md, I ran 'utils/pdb2wrlpymol2_pub.py ', but I only get a '.wrl' file, not two ligand and receptor pdb files. Would you tell me how to do?

Thank you so much!

**Comment by FTD007** [comment]
try batch size 1 since for most of gpu the memory is not enough.

The easiest way is seperate them out in software such as pymol.

**Comment by bbjy** [comment]
> try batch size 1 since for most of gpu the memory is not enough.
> 
> The easiest way is seperate them out in software such as pymol.

Thank you for your reply! 

I try batch size 1,  the "RuntimeError: invalid argument 0. ..." disappears. But another 'CUDA out of memory" occures. So would you tell me the training environment (memory and GPU) of yours? 

For splitting the ligand and receptor, I thought that you processed it by coding. In that case, I will try the software, thank you!

**Comment by FTD007** [comment]
It should be 12GB.

If you have a large complex dataset and want to split ligand and receptors, you can use pymol's python module. One thing I noticed before is some time it is hard to determine which two (or more) chains are the best pair to extract from raw PDB which may include multiple complexes at the same time.

**Comment by bbjy** [comment]
> It should be 12GB.
> 
> If you have a large complex dataset and want to split ligand and receptors, you can use pymol's python module. One thing I noticed before is some time it is hard to determine which two (or more) chains are the best pair to extract from raw PDB which may include multiple complexes at the same time.

Thank you!

I also think it is really hard to determine which two (or more) chains are the best pair to extract from raw PDB. So I consult you for a proper way to split them, since I didn't find the related code in your released code.

**Comment by FTD007** [comment]
The DBD5 dataset is well curated so it do not need manual separation. For customized dataset, I would say check the size of binding site (in term of number of vertices and proportion over the whole size). Set a threshold on size to pick the better pair or throw away some relatively 'bad' PDBs.

**Comment by bbjy** [comment]
> The DBD5 dataset is well curated so it do not need manual separation. For customized dataset, I would say check the size of binding site (in term of number of vertices and proportion over the whole size). Set a threshold on size to pick the better pair or throw away some relatively 'bad' PDBs.

OK! Thank you so much for your careful and patient reply！

**Comment by FTD007** [comment]
Np and feel free to reach me by email if u have question not related to this repo.

**Comment by bbjy** [comment]
OK！ Thanks again.
