### ISSUE TITLE
Ligand and recept PDB file of EpiPred dataset?

### ISSUE THREAD

**Issue by bbjy** [FTD007/PInet#8]
Sorry to trouble you again. 

Would you please tell me how to acquire the ligand (xx-l.pdb) and recept PDB file (xx-r.pdb) of EpiPred dataset? As I understand, the PDB file of ligand and recept is required for interface residue prediction in PredictionPoint2Residue.py, is it so?
It would be great if you could share your data used in the paper!

And confirm another question with you, the alpha factor of the regularization term $L_Hist$ is 100 in your experiments?

Thank you so much!

**Comment by FTD007** [comment]
sorry for getting back late. 
PDBs are the same from EpiPred.
fac is 100
